### PR TITLE
section database

### PR DESCRIPTION
**Pull request by lukaszlaba**
Hi Ritchie
Here is section base feature added to anaStruct. Please check is that ok, or something still must be done before merging it. 
Lukasz

### CODE REVIEW

**Comment by ritchie46** [comment]
Add sectionbase branch. Will make some minor changes.

**Comment by lukaszlaba** [comment]
It looks like after changes user of  SystemElements class lost access to  SectionBase.set_unit_system() method - it is needed if user want to change the unit system used for calculations.

**Comment by ritchie46** [comment]
It is now possible by importing the `section_base_proxy` from the sectionbase module. Sectionbases are an additional library and should not be connected to SystemElements. With the proxy the data is not loaded from io until requested.

`from anastruct.sectionbase.sectionbase import section_base_proxy
section_base_proxy().set_databasename('US')
`

**Comment by lukaszlaba** [comment]
I'm not familiar with this 'proxy' idea and @classmethod decorator.

So in practice it should be used in that way? (it works)

```
from anastruct.fem.system import SystemElements
from anastruct.sectionbase.sectionbase import section_base_proxy 

# calculation with imperial unit system - length in ft, mass in lb, force in lbf

section_base_proxy().set_databasename('US') #switch to US base
section_base_proxy().set_unit_system(lenght_unit='ft', mass_unit='lb', force_unit='lbf') # we want to get section properties in this units

ss = SystemElements()

ss.add_element(location=[[0, 0], [30, 40]], steelsection='WWF79X436', E=4177e6, sw=True, orient='z') # locations in ft , E in lbf/ft2
ss.add_element(location=[[30, 40], [80, 40]], steelsection='WWF79X436', E=4177e6, sw=True, orient='z') # locations in ft , E in lbf/ft2

ss.q_load(element_id=2, q=-10000) # q in lbf/ft

ss.add_support_hinged(node_id=1)
ss.add_support_fixed(node_id=3)

ss.solve()

ss.show_structure() 
ss.show_displacement() # displacement in ft
```

**Comment by lukaszlaba** [comment]
What is your opinion about this ?

**Comment by ritchie46** [comment]
Hi, The sectionbase doesn't require a proxy anymore. However the sectionbase is not part of the SystemElements. It can now be imported.

It also has options to inspect the library.

```
from anastruct.sectionbase import section_base

# show available units. 'length', 'mass' and 'force'
section_base.available_units['length']

# set units
section_base.set_unit_system(length='m', mass_unit='kg', force_unit='N')

# show available sections
section_base.available_sections
```

**Pull request merged**
