### PR TITLE
dxfloader_feature_added

### PR DESCRIPTION
**Pull request by lukaszlaba**
There is dxfloader feature ready to be merged. (This feature need explanation and example in project docs. Same as sectionbase feature.)

### CODE REVIEW

**Comment by ritchie46** [comment]
Hi, thanks for the PR. I need some time to merge. I see you've used your own utility Point class. I will rewrite this to use the same utility class as the rest of the program. At first glance I see, you create element dynamically with `exec`. Could you explain a bit about why we need to do it that way?

**Comment by lukaszlaba** [comment]
Hi, 

I'm not sure that it is a good idea to use vertex class in to dxfloader feature - vertex is used for FEM analysis general. DxfLoader should be independent module with all it need inside. Maybe it is good idea to move vertex.py and basic.py to fem directory for that reason. (?)

Right, it is not good practice to use exec(). But the idea is to put some pseudo code inside the dxf model space (near the point or line) and execute it with coordinates taken form dxf points and lines. I hope you have opened example dxf and understand this idea. So for now I have no idea how to do it other way. I you have any advice I can try to change it.

**Comment by ritchie46** [comment]
No, I don't think vertex should be in FEM, because it has got nothing to do with Fem. And I also want to modify it probably in the future, to use more numpy. I also am looking at your code and trying to implement it a bit more in numpy so that it follows the cody style of the rest of the package. Could you tell me about more about the `distance` measure in the Line class. Is that perpendicular distance? 

And I am not familiar with DWGs. I understand that your read texts, and that these texts contain point information. Is that correct?

**Comment by lukaszlaba** [comment]
Here you can find explanation of distance() method for line class

https://www.dropbox.com/s/h8m3avpdi9b608x/line_distance_method.pdf?dl=0

**Comment by lukaszlaba** [comment]
The line equation is Ax+By+C=0

**Comment by ritchie46** [comment]
Hi, I've merged your PR and made some changes to follow the coding style of the rest of the library more (numpy, pep-8). I see there is `anastruct` code in the DXF. How would this DXF be made? Is there some documentation on how to generate this file?

**Comment by ritchie46** [comment]
Hi, I've merged your PR and made some changes so that it follows the coding style of the library more (numpy, pep-8). 

https://github.com/ritchie46/anaStruct/tree/lukaszlaba-dxfloader_feature

I also see that there is anastruct code in the DXF files. How should these files be generated? Is there some documentation on that?

**Comment by lukaszlaba** [comment]
General there is no need to open dxf as text file and analyses it (!). You just should use one of available programs (Autocad, DraftSight, NanoCad, Librecad etc.) to draw the model (lines and texts)  and save it as dxf and then use dxf_loader feature to get it as anaStruct model. Autocad is commercial,  DraftSight and NanoCad is freeware , LibreCad i free software. 
Here is how it looks like with Autocad
https://youtu.be/ydhOSAow6j0

**Pull request closed without merging**
